### ISSUE TITLE
Verify this compiles on ARM systems

### ISSUE THREAD

**Issue by warmwaffles** [elixir-sqlite/exqlite#109]
Currently I have no idea if this will compile and play nice on ARM. In theory it should because nothing is dependent on x86 / x64 specific things.

**Comment by kevinlang** [comment]
For this and #26 , we could add CI (even if only temporarily)

**Comment by warmwaffles** [comment]
Does github actions support an arm system for this? I have never set up a CI for ARM before. I've done plenty of rails, django, etc... deployments

**Comment by axelson** [comment]
I've tested this on my Raspberry Pi 3B+ (running nerves). So the basics do work on ARM.

**Comment by warmwaffles** [comment]
Excellent to hear. I may need to stand up an arm system to ensure the test suite runs fine on it.

@axelson were you able to run `mix test` and `EXQLITE_INTEGRATION=true mix test`? Assuming you cloned this repo.

**Comment by axelson** [comment]
I have not run that, it would actually not be straightforward on nerves because mix is not installed (only uses elixir releases).
