### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by kevinlang** [elixir-sqlite/exqlite#120]
Once #26 is fixed, we will want to add a Windows CI to ensure that it stays building properly.

**Comment by cw789** [comment]
Reminder for my links in: https://github.com/elixir-sqlite/exqlite/pull/121

**Comment by kevinlang** [comment]
Blocked by https://github.com/erlef/setup-elixir/issues/12

**Comment by kevinlang** [comment]
Looks like this is unblocked now.

https://github.com/erlef/setup-beam/issues/51

**Comment by warmwaffles** [comment]
Oh this is awesome.
