### ISSUE TITLE
Update GitHub repo "About" section

### ISSUE THREAD

**Issue by cw789** [elixir-sqlite/exqlite#122]
> An SQLite3 Elixir library ~~with adapter for Ecto3~~.

As the adapter moved, it should be removed here also.

**Comment by warmwaffles** [comment]
@ConnorRigby can you do this? I do not have permission to modify the about section.

**Comment by kevinlang** [comment]
Or better yet, give us the permissions required to do so :wink:

**Comment by ConnorRigby** [comment]
@kevinlang @warmwaffles I've updated both of you all to be `owner`s of the org.

**Comment by warmwaffles** [comment]
Done. Thanks @ConnorRigby  and thank you @cw789 for bringing that to our attention.
