### ISSUE TITLE
Show Error :statement in message string

### ISSUE THREAD

**Issue by kevinlang** [elixir-sqlite/exqlite#145]
Hit an issue where my DDL was incorrect. The Ecto/db_connection/etc machinery only logged the `:message` of the `Error` struct, which did not have enough information.

I ended up patching the `Error` struct to have this:

```
@impl true
def message(struct), do: "#{struct.message}\n#{struct.statement}"
```

Thoughts?

**Comment by warmwaffles** [comment]
Yea let's do that. It'll save a lot of issues for us.
