### ISSUE TITLE
`update_all` with select raises error when no rows are updated

### ISSUE THREAD

**Issue by rupurt** [elixir-sqlite/exqlite#147]
The ecto spec for `Ecto.Repo.Assoc.query` expects a list of rows but currently the `ecto_sqlite3` adapter returns `nil` when there were no rows updated from the query.

https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/assoc.ex#L10

This results in the following error:

```bash
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Exqlite.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, List, Date.Range, Stream, Range, Map, HashDict, GenEvent.Stream, MapSet, HashSet, IO.Stream, Function, File.Stream
```

P.S. Thank you so much for making this adapter! I looked into creating it a year ago but didn't know where to start :1st_place_medal:

**Comment by kevinlang** [comment]
https://stackoverflow.com/questions/928865/find-sqlite-column-names-in-empty-table

It looks like our solution will not be as clean as the Postgrex one. As far as I can tell SQLite3 itself does not differentiate too well between the two "empty returnset" and "no returnset" cases...

**Comment by rupurt** [comment]
@kevinlang thanks for looking into this so quickly.

FWIW `update_all` with select works as expected when >= 1 row was updated. It's just the 0 rows updated case that is throwing the error.

I need the select for my feature so the way I've worked around it for now is to `try/rescue`. It's a total hack but does the job...

```elixir
try do
  case OrderRepo.update_all(update_order_query, []) do
    # TODO: Not currently used due to SQLite adapter raising error
    {0, []} ->
      OrderRepo.rollback(:invalid_status)

    {1, [current_order]} ->
      case OrderRepo.insert(order_transition_changeset) do
        {:ok, _} -> current_order
        {:error, reason} -> OrderRepo.rollback(reason)
      end

    {:error, reason} ->
      OrderRepo.rollback(reason)
  end
rescue
  # TODO: Remove this once SQLite adapter is fixed
  # https://github.com/elixir-sqlite/ecto_sqlite3/issues/30
  Protocol.UndefinedError ->
    OrderRepo.rollback(:invalid_status)
end
```
