### ISSUE TITLE
Prepare for upgrade to 3.36.0

### ISSUE THREAD

**Issue by warmwaffles** [elixir-sqlite/exqlite#152]
https://sqlite.org/releaselog/3_36_0.html

We can remove `-DSQLITE_ENABLE_DESERIALIZE` since that will be enabled by default now.

**Comment by mindreframer** [comment]
@warmwaffles here one helper script: https://github.com/elixir-sqlite/exqlite/pull/159

**Comment by warmwaffles** [comment]
Excellent, thanks @kevinlang and @mindreframer for making this happen.
