### ISSUE TITLE
Disable debug (or strip binary)

### ISSUE THREAD

**Issue by ewildgoose** [elixir-sqlite/exqlite#172]
Hi, I see at the top of the makefile we have:

CFLAGS ?= -g

The output binary for me (on arm32bit) is
  9398756 Oct 16 16:51 lib/exqlite-0.6.4/priv/sqlite3_nif.so

However, after stripping I get:
  1589804 Oct 25 10:39 lib/exqlite-0.6.4/priv/sqlite3_nif.so

I'm building to a semi-embedded type system, so this is quite a considerable disk saving.

Would you consider making the stripped, non debug exe the standard situation and a flag to toggle on debugging? Alternatively do you have a suggestion on how to disable the debug as part of my release build please?

Thanks for considering this

**Comment by warmwaffles** [comment]
@ewildgoose since we disabled debug in the build now by default I think this issue is closed. However, the issue of possibly using OS provided sqlite3 is a tempting proposition for me.

**Comment by ewildgoose** [comment]
I agree that we can close the debug issue. Thanks!

I want to use this in an embedded environment, and this would be a big space saving for me to dynamically link to the OS provided libs. What can I do to help/sponsor this, etc?

(Also if wishes were free, I am quite excited by the "STRICT" tables feature of the most recent release:
https://www.sqlite.org/releaselog/3_37_0.html - what if anything needs doing to enable this?)

**Comment by warmwaffles** [comment]
@ewildgoose doing that is quite an undertaking for `ecto_sqlite` as we would not be allowed to use `TEXT_DATETIME`.

We had some discussion here but I am unsure of the extent that it can be integrated https://github.com/elixir-sqlite/ecto_sqlite3/issues/60

**Comment by warmwaffles** [comment]
@ewildgoose you can now use the system installed libraries instead of compile sqlite from source https://github.com/elixir-sqlite/exqlite/pull/186
