### ISSUE TITLE
Update to sqlite 3.37

### ISSUE THREAD

**Issue by fire** [elixir-sqlite/exqlite#175]
version 3.37.0. has support a strict mode I want to use.

**Comment by fire** [comment]
Copying https://www.sqlite.org/2021/sqlite-amalgamation-3370000.zip seem to work as expected.

**Comment by warmwaffles** [comment]
@fire there is a script that will do all this for us :D https://github.com/elixir-sqlite/exqlite/blob/main/bin/download_sqlite.sh

Since I have time this morning I'll knock that out.
