### ISSUE TITLE
Settings HAVE_USLEEP flag on *nix systems

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-sqlite/exqlite#185]
While looking into improving concurrent writes with sqlite I noticed that sqlite is compiled without the `HAVE_USLEEP` flag, which means sqlite's busy resolution sleeps for a second between retries, which means for the default `busy_timeout` of `2000`(ms) one will get 2 retry attempts before getting a busy response, even if between those attempts the db might have been idle'ing. It seems the `usleep()` syscall should nowadays be available on most *nix systems. I've not yet confirmed that for nerves, though I doubt it's not available there as well.

What do you think about enabling that flag? I think it might even be good to have it as a default on *nix systems.

**Comment by LostKobrakai** [comment]
A quick discussion on slack confirmed this being fine on nerves systems.

**Comment by warmwaffles** [comment]
@LostKobrakai yea it sounds good to enable that. I can do the PR or you can. It should be pretty easy to add to the makefile for both linux and windows.

**Comment by warmwaffles** [comment]
Maybe need to do a preflight compile check for `have_usleep` like autoconf does.

**Comment by warmwaffles** [comment]
https://www3.sqlite.org/cgi/src/file?name=Makefile.linux-gcc&ci=3ed6eb2fab5d9570 a template for linux-gcc.

**Comment by LostKobrakai** [comment]
I'm not sure how this interacts with windows. An actual check would be great, but that's for sure beyond my capabilities of dealing with C/Makefiles :D

**Comment by warmwaffles** [comment]
Haha, I'll take a look then, not a problem

**Comment by warmwaffles** [comment]
Enabled by default now https://github.com/elixir-sqlite/exqlite/commit/8dbf88b49ea4dd9d3779bc9b4d15b4277f9f0ac0

**Comment by mdwaud** [comment]
Thanks for the quick turnaround, @warmwaffles! This'll be a big help.

**Comment by warmwaffles** [comment]
No problem. I'd love to see any benchmarks you come up with as a result of having this enabled.
