### ISSUE TITLE
Use a struct as response from executed query to get the rows and columns

### ISSUE THREAD

**Issue by aleDsz** [elixir-sqlite/exqlite#202]
Hi!

Firstly, I want to say that I loved the project and it's great to have support for SQLite in Elixir.

We have been building a new feature to support `SQLite` through `livebook` app and `kino_db` library, which allows users to input their database path and loads data directly from a Livebook (same as Jupyter Notebook).

And one of our features is to support the "table" format to visualize data, but `Exqlite` doesn't return a response with columns and rows to make it happen, so I've been thinking about make some contributions to the project.

## Context

In this [PR](https://github.com/livebook-dev/kino_db/pull/2) we added the support to handle `Exqlite` connection and how we should execute the user's query input. And our goal is make it easy to implement the `Table.Reader` protocol from [`table`](https://github.com/dashbitco/table). Since we're not going to add the protocol here, we only need row and columns information.

Then. I've been thinking if it should be a option in the `Exqlite.Connection.connect/1` function or maybe create a new function to fetch all rows and returns the `Exqlite.Query` struct or maybe a new one to represent the result from SQLite.

What you all think? Would be great to talk about, and if y'all have any recommendations or thoughts, please feel free to send.

**Comment by warmwaffles** [comment]
@aleDsz has this been implemented for other database connections? Ones off the top of my head, postgrex, myxql, etc...

I ask because it would be wise to follow a similar pattern if it is.

If it isn't, then I am open to it definitely

**Comment by aleDsz** [comment]
@warmwaffles  Yes, we have Postgrex and MyXQL already implemented and with the `Table.Reader` protocol implemented by `kino_db`.

**Comment by warmwaffles** [comment]
Can you point me to those implementations? Perhaps I could do this change quickly.

**Comment by aleDsz** [comment]
> Can you point me to those implementations? Perhaps I could do this change quickly.

Sure.

We have been using the function `query!/4` present in both ([`postgrex`](https://github.com/elixir-ecto/postgrex/blob/e6f18d849476deb324eb0567eee841dd21bbd3bb/lib/postgrex.ex#L339-L349) and [`mysql`](https://github.com/elixir-ecto/myxql/blob/a986aee7f9d86b735f6e97b9d3442e0bbcb2d0e9/lib/myxql.ex#L262-L275)) and using the same struct format to return the result for both ([`postgrex`](https://github.com/elixir-ecto/postgrex/blob/e6f18d849476deb324eb0567eee841dd21bbd3bb/lib/postgrex/result.ex#L16-L23) and [`myxql`](https://github.com/elixir-ecto/myxql/blob/a986aee7f9d86b735f6e97b9d3442e0bbcb2d0e9/lib/myxql/result.ex#L25-L32))

`query!/4`
```elixir
  def query!(conn, statement, params, opts \\ []) do
    case query(conn, statement, params, opts) do
      {:ok, result} -> result
      {:error, err} -> raise err
    end
  end
```

`Result struct`
```elixir
  defstruct [
    :columns,
    :connection_id,
    :last_insert_id,
    :num_rows,
    :rows,
    :num_warnings
  ]
```

Probably not all information will be available, but would be nice to have some of then.

Both have the same function and the same struct format to be handle by [`kino_db`](https://github.com/livebook-dev/kino_db/blob/171e2fe00898c7e0f2cec486badc269134e47f1d/lib/kino_db.ex#L1-L15)

**Comment by aleDsz** [comment]
One single function to receive the conn, the query, parameters bindings and extra options (if possible, offcourse)

**Comment by warmwaffles** [comment]
That looks simple enough.

**Comment by warmwaffles** [comment]
I think this could be as simple as 

```elixir
  def query(conn, statement, params, opts \\ []) do
    query = %Query{name: "", statement: IO.iodata_to_binary(statement)}

    case DBConnection.prepare_execute(conn, query, params, opts) do
      {:ok, _, result} ->
        {:ok, result}

      {:error, _} = error ->
        error
    end
  end

  def query!(conn, statement, params, opts \\ []) do
    case query(conn, statement, params, opts) do
      {:ok, result} -> result
      {:error, err} -> raise err
    end
  end
```

**Comment by warmwaffles** [comment]
I haven't been using the top level `Exqlite` module and I think replicating a similar interface that postgrex has is a good idea. I'll make a PR for that change with some tests for it as well.

**Comment by warmwaffles** [comment]
@aleDsz https://github.com/elixir-sqlite/exqlite/pull/203 mind checking this branch out and giving your thoughts?

**Comment by aleDsz** [comment]
> @aleDsz #203 mind checking this branch out and giving your thoughts?

I'm checking it right now

**Comment by aleDsz** [comment]
To me, it's all good to connect and make queries.

![image](https://user-images.githubusercontent.com/6402997/166937077-947e7408-019c-4f63-970a-65e9bc1ef2ab.png)

I've talking with Jose about maybe implementing the `table` dependency as optional here and implement the table reader protocol to convert columns and rows, like we did in [`postgrex`](https://github.com/elixir-ecto/postgrex/pull/601).

WDYT?

**Comment by warmwaffles** [comment]
That sounds good to me. I can roll that into my PR above as well.

**Comment by aleDsz** [comment]
> @aleDsz done. This is going to go out with release `0.11.0` here shortly
> 
> [aa6fb8a](https://github.com/elixir-sqlite/exqlite/commit/aa6fb8a2b4e86212942ebd4884d4a1ab01d13592)

This is awesome, I can't wait to be released so we can ship our feature too
Thank you for the awesome work ❤️ 💛 🖤 💙 💚 💜

**Comment by aleDsz** [comment]
@warmwaffles Hey, I have a question about this new API. Should we use `Exqlite.Connection` or `Exqlite` directly? I ask because using a PID for SQLite it only uses a file to connect and doesn't support pooling.

Also, should Exqlite raise if he tries to start with `DbConnection` and we didn't pass a valid `:database` option?

**Comment by warmwaffles** [comment]
@aleDsz How are you interacting with postgres? It has a `Postgrex.Protocol` which is the same as `Exqlite.Connection` both implement the `DBConnection` protocol.

**Comment by warmwaffles** [comment]
As for the raising on connection, I don't know if that is an expected behavior for the `DBConnection` protocol. We just return an `{:ok, _} | {:error, _}` tuple

https://github.com/elixir-sqlite/exqlite/blob/0c385ac1e4deb27f65c55cc11328b044240b8a21/lib/exqlite/connection.ex#L140-L155

**Comment by aleDsz** [comment]
> @aleDsz How are you interacting with postgres? It has a `Postgrex.Protocol` which is the same as `Exqlite.Connection` both implement the `DBConnection` protocol.
> 
> With regards to pooling, when I built this library I tried to mimic closely what postgrex and myxql do. You _should_ be able to use the same pooling interface you utilize for those other two adapters. Ecto does most of that dispatching though.

We are using `Kino.start_child/1` to start `Postgrex`/`Exqlite` in the same way and we send the `query!/4` to query.

**Comment by aleDsz** [comment]
I mean, the API is super simple now and it works. But, now `Exqlite` has two APIs, is that okay or we should adapt to `Exqlite.Connection`? This is the point for my first question.

**Comment by warmwaffles** [comment]
Heh, `Exqlite` has a few interfaces to be honest. But they either go through the `DBConnection` interface or directly with `Exqlite.Sqlite3`.

It's not a huge issue at the moment.

> We are using `Kino.start_child/1` to start `Postgrex`/`Exqlite` in the same way and we send the `query!/4` to query.

Is the `Postgrex` processed pooled?
