### ISSUE TITLE
Ecto.Query.order_by returning incorrect order

### ISSUE THREAD

**Issue by hez** [elixir-sqlite/exqlite#208]
I've tried to narrow this down to the smallest dataset I could (results very as I remove entries and eventually it does the correct sorting). Running this through the raw Exqlite `query!` returned the same results as through Ecto.

What I expect to happen:

Using order_by should give the same order as running the raw query in sqlite3 command line.

What actually happens:

Order is not identical.

Smallest sample I could create: https://gist.github.com/hez/41e8ab04a8b0f3b419fad6c66083ad04

**Comment by warmwaffles** [comment]
Which version are you running? We recently had some changes around ordering here https://github.com/elixir-sqlite/exqlite/pull/205

**Comment by hez** [comment]
> Which version are you running? We recently had some changes around ordering here #205

0.11.1

Just noticed there is an 0.11.2, will check that

**Comment by hez** [comment]
It does appear that #205 and the release of 0.11.2 fixed it! Thanks!
