### ISSUE TITLE
[question] sqlite extension alignment problem in exqlite, but not in sqlite3

### ISSUE THREAD

**Issue by ruslandoga** [elixir-sqlite/exqlite#209]
👋

I understand that it's unlikely to be a problem in `exqlite`, but just in case you have any idea as to what I'm doing wrong.

---

Repo: https://github.com/ruslandoga/sqlite-zig-problem

I'm trying to write an extension for sqlite in [zig](https://ziglang.org) and I'm getting an [alignment panic](https://ziglang.org/documentation/master/#Alignment) when fetching sqlite's aggregate context. But, I'm only getting it when executing the query from elixir, not from `sqlite3` cli.

Meaning,

```sql
sqlite> .load dist/extc
sqlite> .load dist/extzig

-- this uses c extension
sqlite> with recursive ten(x) as (select 1 union all select x+1 from ten where x<10) select sumc(x) from ten;
55.0

-- this uses zig extension
sqlite> with recursive ten(x) as (select 1 union all select x+1 from ten where x<10) select sumzig(x) from ten;
55.0
```

but in elixir:

```elixir
iex(1)> E.sumc
# [debug] QUERY OK db=0.6ms decode=1.3ms idle=738.5ms
# with recursive ten(x) as (select 1 union all select x+1 from ten where x<10) select sumc(x) from ten []
%Exqlite.Result{
  columns: ["sumc(x)"],
  command: :execute,
  num_rows: 1,
  rows: [[55.0]]
}

iex(2)> E.sumzig
thread 8760720 panic: incorrect alignment
```

**Comment by ruslandoga** [comment]
@warmwaffles here's the zig file: https://github.com/ruslandoga/sqlite-zig-problem/blob/master/src/ext.zig

Here's how I'm compiling it on mac: https://github.com/ruslandoga/sqlite-zig-problem/blob/0c206a50001139ff633a74ce0b909790588200c6/Makefile#L10-L12

Zig docs suggest downloading "nightly" master builds so I'm using 

```
> zig version
0.10.0-dev.2473+e498fb155
```

**Comment by warmwaffles** [comment]
@ruslandoga are you also on an M1 mac?

**Comment by ruslandoga** [comment]
@warmwaffles ah, yes.

**Comment by ruslandoga** [comment]
@warmwaffles small update: I printed the pointer and it was `102a7acdc` when called from Elixir and `120016530` when called from `sqlite3-cli`. Converting these to base10 yields 4831929648 and 4339510492. And `4831929648/8 = 603991206` but `4339510492/8 = 542438811.5` and that's what `@alignCast` checks.

**Comment by ruslandoga** [comment]
[`std.mem.alignForward` workaround works](https://github.com/ruslandoga/sqlite-zig-problem/pull/1)

**Comment by warmwaffles** [comment]
I 100% trust `enif_alloc` to do the right alignment based on the architecture OTP was compiled for.

**Comment by warmwaffles** [comment]
@ruslandoga are you still having alignment issues?

**Comment by ruslandoga** [comment]
@warmwaffles hi! I wasn't able to find the cause of this issue at the time so I moved away from using extensions in my app. I still plan to learn more about low-level programming and find out what's going on, though :)

**Comment by warmwaffles** [comment]
Alright

**Comment by ruslandoga** [comment]
👋

I think it was due to shifting the address by four bytes `sizeof(int)`

**Comment by warmwaffles** [comment]
Hmmm, I wonder if the `ssize_t` type would be a better type to use since on a 64 bit system it should be up to 64 bits and on a 32 bit system it should be up to 32 bits.
