### ISSUE TITLE
Feature request: Add support for Data Change Notification Callbacks

### ISSUE THREAD

**Issue by OldhamMade** [elixir-sqlite/exqlite#221]
It would be great if exqlite supported Data Change Notification Callbacks, eg. `set_update_hook`, similar to [mmzeeman/esqlite](https://github.com/mmzeeman/esqlite). `esqlite` is great, however it is very Erlang-focused and the original Elixir wrapper library for it has been abandoned. It would be very useful to be able to act on hooks within a project that is using [ecto_sqlite3](https://hex.pm/packages/ecto_sqlite3).

**Comment by ruslandoga** [comment]
@warmwaffles I wonder if it can be a separate connection behaviour like https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/replication_connection.ex.

**Comment by warmwaffles** [comment]
I'm not entirely sure how this would function because the update hooks would only work on the currently connected db connection / exqlite connection.

Definitely an interesting use case that doesn't fit the current paradigm that `DbConnection` and `Ecto` have defined.

**Comment by OldhamMade** [comment]
> Can you provide me a concrete use case that this would fit in to?

It would allow someone using a SQLite database to get close to mimicking the LISTEN/NOTIFY functionality from Postgres, which is my specific use-case: I'd like to act on table updates caused by DB triggers from within Elixir code.

> Definitely an interesting use case that doesn't fit the current paradigm that DbConnection and Ecto have defined.

I'm not sure that it needs to fit with that paradigm. I think it is more akin to `Postgrex.Notifications`, a useful extra.

**Comment by warmwaffles** [comment]
I didn't realize `Postgrex` had that ability. I'll take a look at how they resolved the `LISTEN` / `NOTIFY`. We may be able to utilize a similar functionality.

**Comment by mdwaud** [comment]
+1 for interest in this capability
