### ISSUE TITLE
SQLCipher: How to set `cipher_compatibility`?

### ISSUE THREAD

**Issue by adri** [elixir-sqlite/exqlite#227]
Thank you so much for this library! 

I followed the README to use SQLCipher, and compiling worked great. 

When trying to open an encrypted database I got this error:
```
file is not a database
```

The problem is that the database was encrypted with SQLCipher version 3 while I'm using version 4. 
It works when I manually set `set_pragma(db, "cipher_compatibility", 3)` in `Exqlite.Connection.set_key`.  This is the equivalent to doing:
```sql
PRAGMA cipher_compatibility = 3;
```

I was wondering: how to implement this properly? 

Any call after `set_key` without setting the version, like https://github.com/elixir-sqlite/exqlite/blob/d1f71760bde4a6558734446065acf60028b0969b/lib/exqlite/connection.ex#L447 will lead to `file is not a database` errors. I guess `cipher_compatibility` is not a standard `pragma` value but specific to SQLCipher. I'm thankful for any tips.

**Comment by warmwaffles** [comment]
@ConnorRigby would you be able to help out with this since you dabbled in with sqlcipher in #186.

**Comment by warmwaffles** [comment]
Sorry @adri I haven't messed with the cipher portion of sqlite yet. I haven't had the need to yet. When I get some time I'll take a look and I think possibly add integration tests for it.

**Comment by warmwaffles** [comment]
If we have a good handle on how custom ciphers would be setup, we could make a private function that accepts those inputs 

```elixir
def set_cipher(db, options) do
  # do the setup stuff here
end
```

Then just shim it in right after `set_key/2` in the `with` block.

**Comment by warmwaffles** [comment]
hmmm I think maybe a `set_custom_pragmas` would work better here.

That way in your elixir configs with ecto you could do

```elixir
config :my_app, MyApp.Repo,
  database: "path/to/my/database.db",
  pragmas: [
    cipher_compatibility: 3,
    cipher_page_size: 8192,
    cipher_hmac_algorithm: "HMAC_SHA256",
    # sqlite3 pragma that we don't expose as a connection opt
    foreign_keys: true
  ]
```

This would allow for someone to use something other than sqlcipher (if it exists)
