### ISSUE TITLE
Precompilation support

### ISSUE THREAD

**Issue by josevalim** [elixir-sqlite/exqlite#230]
Hi @warmwaffles!

A couple months ago, the amazing @cocoa-xu added support for [precompilation in `elixir_make`](https://hexdocs.pm/elixir_make/precompilation_guide.html). Is this something of interest to you and the project? This can help specially with Windows users.

If you are, we would be happy to fund towards making this happen, or getting someone to make it happen. :)

Thank you.

**Comment by josevalim** [comment]
Btw, once precompilation is operational, the workflow is for releasing new versions is slightly different. You would tag, push the tag, wait for GH Actions to precompile, and then run a command to download the precompiled artefacts, MD5 them, and publish the package.

There is an example with everything hooked up, including CI here: https://github.com/cocoa-xu/cc_precompiler_example

**Comment by warmwaffles** [comment]
@josevalim I'll take a look at this. The only thing this would conflict with is https://github.com/elixir-sqlite/exqlite#advanced-configuration specifically the "Database Encryption" portion.

**Comment by josevalim** [comment]
@warmwaffles you have full control over when to use the precompiled stuff. So if that env var is set, you disable precompiled download. If something is missing, we can add the missing features to make this possible. :)

**Comment by warmwaffles** [comment]
Oh that's brilliant. I'll take a stab at this.

**Comment by cocoa-xu** [comment]
Hi @warmwaffles, also please feel free to ask me anything, I'll be very happy to help you! :)

**Comment by fire** [comment]
I would like to also enable this for https://github.com/fire/elixir_mvsqlite. Rust complication is difficult

**Comment by josevalim** [comment]
@fire for Rust there is https://github.com/philss/rustler_precompiled/

**Comment by fire** [comment]
I am not using rustler, it is the build make system of exqlite + a library in c built by rust.

**Comment by warmwaffles** [comment]
@cocoa-xu and @josevalim Just trying to figure out how precompiled binaries work. When you do a `mix deps.get` will that also pull the precompiled binaries from github, or when I invoke `mix hex.publish` locally, those are pulled down and pushed up to hex.pm?

**Comment by warmwaffles** [comment]
Or you know, I could read https://github.com/cocoa-xu/cc_precompiler/blob/main/PRECOMPILATION_GUIDE.md 😆

**Comment by warmwaffles** [comment]
Since I want to support as best as possible the last 3 versions of OTP (right now 25, 24, and 23), I'll need to build precompiled binaries for each version right? That shouldn't be difficult to do with a matrix, it just makes the precompiled binaries balloon.

**Comment by cocoa-xu** [comment]
> support as best as possible the last 3 versions of OTP (right now 25, 24, and 23), I'll need to build precompiled binaries for each version right?

For these shared libraries (NIFs), as long as `erlang:system_info(nif_version)` stays the same then we don't have to build the precompiled binaries for each OTP version (instead we need to build for each `nif_version` that you'd like to support). ;)

**Comment by warmwaffles** [comment]
Precompilation support added!
