### ISSUE TITLE
Opting out of precompiled binaries

### ISSUE THREAD

**Issue by george-hopkins** [elixir-sqlite/exqlite#238]
On older systems, the precompiled library shipped with #234 is not usable due to an older glibc version. Is it possible to opt out of precompiled artifacts and still use the SQLite version in c_src?

**Comment by warmwaffles** [comment]
@cocoa-xu can you add a section to the README.md about how to skip pre-compilation?

**Comment by cocoa-xu** [comment]
Oh yes, the glibc versions... I'll address this issue in `elixir_make` ASAP. And meanwhile, perhaps @george-hopkins would have to use the last version that works. Sorry for the inconvenience!

**Comment by warmwaffles** [comment]
@george-hopkins https://github.com/elixir-sqlite/exqlite/pull/240 introduces the change for opting out of precompiled artifacts.

**Comment by george-hopkins** [comment]
:tada: Thank you!
