### ISSUE TITLE
phx.new fails for --database sqlite if white spaces exist in the erlang directory

### ISSUE THREAD

**Issue by jdmarshall** [elixir-sqlite/exqlite#249]
Erlang is installed in /Users/jasonmarshall/Library/Application\ Support/ErlangInstaller/24.0/erlang/

and I am seeing error:

mix deps.compile exqlite
==> exqlite
 CC sqlite3_nif.o
clang: error: no such file or directory: 'Support/ErlangInstaller/24.0/erlang/usr/include'
Which looks like the space after "Application" is causing issues.

**Comment by warmwaffles** [comment]
Can you run 

```
mix deps.clean exqlite
V=1 mix deps.compile exqlite
```

**Comment by jdmarshall** [comment]
`Dark-Star:weald jasonmarshall$ mix deps.get exqlite
Resolving Hex dependencies...
Resolution completed in 0.165s
Unchanged:
  castore 1.0.1
  cc_precompiler 0.1.7
  cowboy 2.10.0
  cowboy_telemetry 0.4.0
  cowlib 2.12.1
  db_connection 2.5.0
  decimal 2.1.1
  ecto 3.10.1
  ecto_sql 3.10.1
  ecto_sqlite3 0.10.2
  elixir_make 0.7.6
  esbuild 0.7.0
  expo 0.4.1
  exqlite 0.13.10
  file_system 0.2.10
  finch 0.16.0
  floki 0.34.2
  gettext 0.22.1
  hpax 0.1.2
  jason 1.4.0
  mime 2.0.3
  mint 1.5.1
  nimble_options 1.0.2
  nimble_pool 1.0.0
  phoenix 1.7.2
  phoenix_ecto 4.4.1
  phoenix_html 3.3.1
  phoenix_live_dashboard 0.7.2
  phoenix_live_reload 1.4.1
  phoenix_live_view 0.18.18
  phoenix_pubsub 2.1.1
  phoenix_template 1.0.1
  plug 1.14.2
  plug_cowboy 2.6.1
  plug_crypto 1.2.5
  ranch 1.8.0
  swoosh 1.10.2
  tailwind 0.2.0
  telemetry 1.2.1
  telemetry_metrics 0.6.1
  telemetry_poller 1.0.0
  websock 0.5.1
  websock_adapter 0.5.1
* Getting exqlite (Hex package)
Dark-Star:weald jasonmarshall$ V=1 mix deps.compile exqlite
==> exqlite
mkdir -p /Users/jasonmarshall/Projects/weald/_build/dev/lib/exqlite/priv
mkdir -p /Users/jasonmarshall/Projects/weald/_build/dev/lib/exqlite/obj
 CC sqlite3_nif.o
cc -c -I/Users/jasonmarshall/Library/Application Support/ErlangInstaller/24.0/erlang/usr/include -I"/Users/jasonmarshall/Library/Application Support/ErlangInstaller/24.0/erlang/erts-12.0/include" -Ic_src -DNDEBUG=1 -O2 -fPIC -DSQLITE_THREADSAFE=1 -DSQLITE_USE_URI=1 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS=1 -DSQLITE_DQS=0 -DHAVE_USLEEP=1 -DALLOW_COVERING_INDEX_SCAN=1 -DENABLE_FTS3_PARENTHESIS=1 -DENABLE_LOAD_EXTENSION=1 -DENABLE_SOUNDEX=1 -DENABLE_STAT4=1 -DENABLE_UPDATE_DELETE_LIMIT=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS4=1 -DSQLITE_ENABLE_FTS5=1 -DSQLITE_ENABLE_GEOPOLY=1 -DSQLITE_ENABLE_MATH_FUNCTIONS=1 -DSQLITE_ENABLE_RBU=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_OMIT_DEPRECATED=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -o /Users/jasonmarshall/Projects/weald/_build/dev/lib/exqlite/obj/sqlite3_nif.o c_src/sqlite3_nif.c
clang: error: no such file or directory: 'Support/ErlangInstaller/24.0/erlang/usr/include'
make: *** [/Users/jasonmarshall/Projects/weald/_build/dev/lib/exqlite/obj/sqlite3_nif.o] Error 1
could not compile dependency :exqlite, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exqlite", update it with "mix deps.update exqlite" or clean it with "mix deps.clean exqlite"
==> weald
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.

Dark-Star:weald jasonmarshall$ gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Dark-Star:weald jasonmarshall$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
`

**Comment by jdmarshall** [comment]
So it looks like the first argument to cc is not escaped but the second is.

**Comment by warmwaffles** [comment]
@jdmarshall I can get a fix up just shortly. It's the `ERL_CFLAGS` in the makefile.

**Comment by warmwaffles** [comment]
It has been fixed in `v0.13.11`

**Comment by jdmarshall** [comment]
Good deal. Thanks for looking into it.

**Comment by jdmarshall** [comment]
Sorry for the lag. Confirmed fixed.
