### ISSUE TITLE
Unable to compile w/ OTP26

### ISSUE THREAD

**Issue by dtcaciuc** [elixir-sqlite/exqlite#252]
I believe the root cause is https://github.com/erlang/otp/issues/6916

However, even when I change Makefile.win to have `-s erlang halt` at the end of that line, make process hangs there without proceeding any further. Not sure where to go from here.

OTP 26.0.1
Elixir 15.0
Windows 11 Version 10.0.22621 Build 22621

**Comment by warmwaffles** [comment]
@dtcaciuc I recreated the hanging for the process in that PR above. I'll need some time to work through it. For now I recommend staying with OTP25 until I can get it resolved.

I don't have access to a windows dev environment to muck around on easily. I suspect the ultimate fix is to combine both of the makefiles into one.

**Comment by dtcaciuc** [comment]
Thank you for looking into this!

**Comment by warmwaffles** [comment]
I'll take a look

**Comment by warmwaffles** [comment]
@dtcaciuc published under v0.13.14

**Comment by warmwaffles** [comment]
I still need to pull together the pre-compilation to support otp26
