### ISSUE TITLE
Does not properly compile on Windows

### ISSUE THREAD

**Issue by warmwaffles** [elixir-sqlite/exqlite#26]
I have not tried to test this on windows yet. I do have access to a windows machine, but no idea how we can get this automated.

**Comment by kevinlang** [comment]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

Looks like CI has support for running on windows. We can use that in conjunction with https://github.com/erlef/setup-elixir, I think

**Comment by warmwaffles** [comment]
Excellent. I think we can utilize that.

**Comment by cw789** [comment]
First "quick" try, by the way I'm no pro in compiling this things.
Probably something with my "Microsoft C++ Build Tools" install is still wrong...

```
==> exqlite

Microsoft (R) Program Maintenance Utility Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        del /Q /F priv
        erl -noshell -s init stop -eval "io:setopts(standard_io, [{encoding, unicode}]), io:format(\"ERTS_INCLUDE_PATH=~ts/erts-~ts/include/\", [code:root_dir(), erlang:system_info(version)])." > Makefile.auto.win
        nmake /                   /F Makefile.win priv\sqlite3_nif.dll

Microsoft (R) Program Maintenance Utility Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        if NOT EXIST "priv" mkdir "priv"
        cl /O2 /EHsc /I"sqlite3" /I"c:/Users/cw/scoop/apps/erlang/23.2.7/erts-11.1.8/include/" /LD /MD /Fepriv\sqlite3_nif.dll sqlite3\sqlite3.c c_src\sqlite3_nif.c c_src\queue.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

sqlite3.c
sqlite3\sqlite3.c(1098): fatal error C1083: Cannot open include file: 'stdarg.h': No such file or directory
sqlite3_nif.c
c_src\sqlite3_nif.c(1): fatal error C1083: Cannot open include file: 'assert.h': No such file or directory
queue.c
c1: fatal error C1083: Cannot open source file: 'c_src\queue.c': No such file or directory
Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\nmake.EXE"' : return code '0x2'
Stop.
```

**Comment by kevinlang** [comment]
This line at least is a bug in `Makefile.win`:
```
c1: fatal error C1083: Cannot open source file: 'c_src\queue.c': No such file or directory
Generating Code...
```

The file specifies a `queue.c` that indeed does not exist in the code! Likely an artifact of one of the older sqlite NIFs we adapted. Removing that should fix that issue. 

The rest I have no idea. Looking at the `stdarg.h` thing, it seems like that may indicate some sort of misconfigured build tool, see this issue I found:

https://github.com/microsoft/vscode/issues/75334

**Comment by kevinlang** [comment]
https://cognitivewaves.wordpress.com/makefiles-windows/

Here is a decent guide. I think our best bet will be to just copy the `Makefile` over into `Makefile.win` and slowly modify it until Windows is happy.

**Comment by cw789** [comment]
Thanks.
With `'c_src\queue.c` removed and some tweaks to my build environment it does build. ✔

I'll write a guide for using it on windows, once I have more time to test the build properly.

**Comment by kevinlang** [comment]
Sweet! Submitting a PR with the changes that fixed it will also be greatly appreciated!

Cheers
