### ISSUE TITLE
libSQL support/fork

### ISSUE THREAD

**Issue by lessless** [elixir-sqlite/exqlite#261]
Hey folks, 

I can see increased interest in SQLite in my [tech](https://twitter.com/dhh/status/1705271515997143168) [bubble](https://www.youtube.com/watch?v=fq2PUpgfCi4).

Ahd that's how I learned about [libSQL](https://turso.tech/libsql) which offers several [improvements](https://github.com/tursodatabase/libsql/blob/main/doc/libsql_extensions.md)  including altering columns.

One of the project goals is to maintain 100% backwards compatibility with SQLite yet it still may deserve fork/another project, and I appreciate that it might be beyond the resources that the team currently have. 

This also made me think that Exqlite may benefit from swappable backends. 

_update:_  I played a bit with libSQL and Exqlite and it seems that libSQL is a[ Rust project](https://github.com/tursodatabase/libsql/tree/main/crates) and doing it right means taking completely another route of building native extension against it with Rustler. 

that followed [a brief chat in Turso's Discord](https://discord.com/channels/933071162680958986/1160269821347385465/1160527266451816480)  in the context of an already ongoing conversation which highlighted the exciting capability of embedded replications, which  is definitely beyond the original SQLite scope.

 >Thanks! Embedded replicas require not only that the driver will use libsql instead of sqlite (which is very easy) but also that our http and sync functions are exposed (should be also easy if adopting libsql happened throughtl the rust library, not C).

> Unfortunately we also don't have the bandwidth to support elixir at the moment, but if the driver maintainers want to do that,  we would be happy to help!

Best, 
Yevhenii

**Comment by warmwaffles** [comment]
So I designed `ecto_sqlite3` to have the ability to swap out different sqlite backend implementations. All you need to do honestly is build a new library that implements the `db_connection` interface. I believe this is how you can swap it out easily.

This would allow you to bring in your own rustler compilation process.

Some big things to consider about libsql, if at any point they diverge on the features of the SQL syntax and what is available (native json operators like psql, ltree, etc...) then we will not be able to support that with the `ecto_sqlite3` implementation.

**Comment by jeregrine** [comment]
I dropped in a binary of libsql into ecto_sql and it just worked so its probably not that hard if you need this to work, fork exqlite and add the libsql amalgamation and you are good.

**Comment by jeregrine** [comment]
I just needed to bring in [libsql-amalgamation-0.2.2.tar.gz](https://github.com/tursodatabase/libsql/releases/download/v0.2.2/libsql-amalgamation-0.2.2.tar.gz) in place of sqlite3.h/cc and it "just worked". I'm not sure ecto_sqlite supports alter but nothing stops you from using it manually.

**Comment by warmwaffles** [comment]
That is correct, `ecto_sqlite` does not support alter because well, sqlite doesn't support alter 😉
