### ISSUE TITLE
regenerate docs to fix styling issues

### ISSUE THREAD

**Issue by dvic** [elixir-sqlite/exqlite#267]
![image](https://github.com/elixir-sqlite/exqlite/assets/1214337/3385bf8f-aa2f-4b7b-a36c-9afcd98558c5)

it seems this can be fixed by removing the docs folder and recreating the docs: https://github.com/elixir-lang/ex_doc/issues/1794#issuecomment-1772188370

**Comment by warmwaffles** [comment]
All fixed, thank you!
