### ISSUE TITLE
Load extensions with `Sqlite3` ??

### ISSUE THREAD

**Issue by andyl** [elixir-sqlite/exqlite#275]
`Exqlite.Basic` has functions `enable_load_extension` and `load_extension`.

`Exqlite.Sqlite3` only has function `enable_load_extension`.

Is it possible to load extensions with `Sqlite3` ??

**Comment by warmwaffles** [comment]
Yes using the `Connection` configuration you can:

```elixir
config :exqlite, load_extensions: [ "./priv/sqlite/\#{arch_dir}/rotate" ]
```

Here is a ton of information about the configurations that can be passed to exqlite. Sorry that the information is buried in there. https://hexdocs.pm/exqlite/Exqlite.Connection.html#connect/1 

Just be aware, when you load extensions that they need to be compiled for that machine and must be compatible with the sqlite version.

**Comment by andyl** [comment]
Thanks very much!  Would you like a PR for a small update to README with this docco?

**Comment by warmwaffles** [comment]
@andyl definitely, an example section in the README would be fine.

**Comment by andyl** [comment]
Done.
