### ISSUE TITLE
SQL Cipher with custom path

### ISSUE THREAD

**Issue by lawik** [elixir-sqlite/exqlite#280]
I did a custom install of sqlcipher from source using:

```
./configure --prefix=myproject/priv/sqlcipher --libdir=myproject/priv/sqlcipher/lib
```

It was not enough to set the EXQLITE_SYSTEM env vars. exqlite would fail to find `libsqlcipher.so.0` with this:

```
export EXQLITE_USE_SYSTEM=1
export EXQLITE_SYSTEM_CFLAGS="-I/$(pwd)/priv/sqlcipher/include/sqlcipher"
export EXQLITE_SYSTEM_LDFLAGS="-L/$(pwd)/priv/sqlcipher/lib -lsqlcipher"
```

This worked:

```
export EXQLITE_USE_SYSTEM=1
export EXQLITE_SYSTEM_CFLAGS="-I/$(pwd)/priv/sqlcipher/include/sqlcipher"
export EXQLITE_SYSTEM_LDFLAGS="-L/$(pwd)/priv/sqlcipher/lib -lsqlcipher"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/$(pwd)/priv/sqlcipher/lib"
```

It makes sense but tripped me up so I figured I'd add it here. Might tutorial something later.

Also the key doesn't work if it contains a dash "super-secret" style. Sent a PR on that for Ecto.SQLite3 but couldn't do the edit-and-PR as easy on this repo.

I still don't get an encrypted DB with this setup so that's something I'm investigating :D

**Comment by lawik** [comment]
This might be that I had an incomplete build. Disregard for now :)

**Comment by warmwaffles** [comment]
Ah yes the best kind of bugs. The ones that self resolve. 😉
