### ISSUE TITLE
is there way to run some sqlite command, such as .import

### ISSUE THREAD

**Issue by lei0zhou** [elixir-sqlite/exqlite#295]
for example importing a csv file, could you suggest a way to do that? thanks!

<img width="895" alt="image" src="https://github.com/user-attachments/assets/bef34361-9786-4871-8143-f8350d7cb40f">

**Comment by warmwaffles** [comment]
So the sqlite cli is compiled with that support. Bog standard embedded sqlite does not have this ability. https://sqlite.org/cli.html

Your best bet is to parse the CSV and stream it into the database 

```elixir
"priv/english.csv"
|> File.stream!()
|> CSV.decode()
|> Enum.each(fn row ->
  Repo.insert(....)
end)
```

Or use the CLI to import it manually.
