### ISSUE TITLE
Flag SQLITE_ENABLE_DBSTAT_VTAB not included in the windows build

### ISSUE THREAD

**Issue by schutm** [elixir-sqlite/exqlite#296]
It looks like the flag SQLITE_ENABLE_DBSTAT_VTAB has been added to the generic build, not to the windows build. Is this on purpose?

**Comment by warmwaffles** [comment]
Definitely not. The problem with windows is that I have to maintain two separate makefiles for that crazy world 🙄. I'll get that added for windows.

**Comment by warmwaffles** [comment]
Main issue I have is that the CI for windows tests die randomly with no output.

**Comment by warmwaffles** [comment]
Should be good to go https://github.com/elixir-sqlite/exqlite/releases/tag/v0.24.2
