### ISSUE TITLE
busy_handler hook

### ISSUE THREAD

**Issue by egze** [elixir-sqlite/exqlite#309]
Following the article about [optimal performance for SQLite](https://fractaledmind.github.io/2024/04/15/sqlite-on-rails-the-how-and-why-of-optimal-performance/), one more thing missing in my opinion is the `busy_handler` hook. I have never worked with C bindings, nifs and the like, so I actually don't know if it is already supported or not. (search for `busy_handler hook` in the article)

A quote:
> Luckily, in addition to the busy_timeout, SQLite also provides the lower-level [busy_handler hook](https://www.sqlite.org/c3ref/busy_handler.html). The busy_timeout is nothing more than a specific busy_handler implementation provided by SQLite. Any application using SQLite can provide its own custom busy_handler. The sqlite3-ruby gem is a SQLite driver, meaning that it provides Ruby bindings for the C API that SQLite exposes. Since it provides [a binding for the sqlite3_busy_handler C function](https://github.com/sparklemotion/sqlite3-ruby/blob/055da734dafdbb01bb8cf59dbcdb475ea822683f/ext/sqlite3/database.c#L209-L220), we can write a Ruby callback that will be called whenever a query is queued.

Is it already supported? If yes, how would I use it to write my own hook? And if not - what would it take to support it?

**Comment by warmwaffles** [comment]
It is not available at the moment. Due to the pooled connection nature of `DBConnection` this is not possible.

**Comment by warmwaffles** [comment]
We could introduce a way to define a function to be called using the sqlite busy handler, BUT the supervisor watching the process will die if it reaches the default timeout. Meanwhile, the query will still continue to execute in the background because it is a dirty NIF.

I'll have to think some more about this.

**Comment by egze** [comment]
> What are you trying to accomplish?
I'm just following the article to have the best settings possible on production. I don't have any issues yet myself. But the article does make sense to me, and it would be a shame if sqlite with ecto is less performant than with rails.

**Comment by warmwaffles** [comment]
At some point, you still have to deal with a busy error or a timeout from the connection pool. The busy handler in that rails application is simply deferring when that happens and optimistically retrying until it exhausts itself. We can implement something similar but you still have to contend with the configured timeout when you execute a query with the repo.

**Comment by egze** [comment]
That's understandable, that it won't make the system perfect.

If you can find a way to make the handler work - I think will go a long way towards sqlite adoption. It is a very cool database and the thought of having one service less to manage (postgres) is very very appealing to me.

If it's not possible because of the architecture - that's fine too. Unfortunately I don't know anything about nifs, to offer any help. But I'll educate myself in the coming days :)

**Comment by warmwaffles** [comment]
@egze the way it is now it can handle quite a lot https://www.youtube.com/watch?v=huGVdGLBJEo but I do have plans to make it better.

**Comment by warmwaffles** [comment]
I looked into this some more and I remember some of the reasons why I never implemented the busy handler callback.

* You can not directly call an anonymous function from a NIF. You can only send a message and you only get a return value signaling that the message was sent. It does not block until the execution is done.
* There is no standard library way to make the NIF execution sleep. We _could_ use `unistd.h` but this rules out support on Windows. 
* This runs contrary to the Erlang creed of "let if crash". If a timeout error occurs a retry mechanism should be implemented by the application. This will also allow you finer control on _when_ you want to do the retry and how to go about scheduling it.

**Comment by egze** [comment]
Interesting. So the only way to have it, would be to compile SQLite where the callback is implemented in C, right? Would an extension be able to provide such a callback?

**Comment by egze** [comment]
>  I don't recommend it.

Sorry to keep annoying you 😊 Why wouldn't you recommend it, if this interface if well defined by the SQLite authors? Or you don't recommend in general to bother with this hook?

**Comment by warmwaffles** [comment]
I don't recommend it in the execution environment of Erlang or Elixir.

You can not call erlang/elixir code from a NIF. So there is no way to directly invoke a function or anonymous function. The only way to accomplish a callback into Erlang/Elixir is to send a message to a PID, this send is also a non blocking call. We have no idea if the call was processed. The only thing we know from the aspect of the NIF is that the message was sent. So there is no way to reliably have SQLite know if the function should return 1 or 0. Returning a 0 would cause the handler to stop and emit an SQLite busy error. Constantly returning a 1 would cause it to spin forever.

**Comment by egze** [comment]
Yes, this I get that providing a callback in Elixir/Erlang is not the way to go. I thought that you wouldn't recommend doing it through an extension in C.

Anyway, let's call it a day. I might try it out with a C extension someday and then post a comment back here. Thank you for all the information you've provided.
