### ISSUE TITLE
Improve compilation speed for rebuilds

### ISSUE THREAD

**Issue by warmwaffles** [elixir-sqlite/exqlite#99]
I would like to explore compiling sqlite3 to an object file and then linking it rather than recompiling everything at once. I dread making changes to the nif because the compilation takes so long.

**Comment by warmwaffles** [comment]
I had to revert this with ba639cd3815d3a1276c522ac9c80c7eccec92865

It was compiling the code within the source tree, rather than out of tree.

**Comment by kevinlang** [comment]
This would be very nice to have, indeed.
